Repository 20Scoops-CNX/intern-backend-gitflow, pull requests merged in 2023-11, with the labels that each got.

#4 Change cat model to schema
  package-lock.json
  package.json
  src/app.module.ts
  src/cat/cat.controller.ts
  src/cat/cat.model.ts
  src/cat/cat.module.ts
  src/cat/cat.schema.ts
  src/cat/cat.service.ts
  src/cat/dto/create-cat.dto.ts
  src/cat/dto/update-cat.dto.ts
  src/main.ts
Labels: status: Done, status: Waiting For Review

#11 remove productcontroller & service from appmodule
  src/app.module.ts
Labels: fix

#12 Add swagger for cat and product api
  package-lock.json
  package.json
  src/app.module.ts
  src/cat/cat.controller.ts
  src/cat/cat.schema.ts
  src/cat/cat.service.ts
  src/cat/dto/create-cat.dto.ts
  src/cat/dto/update-cat.dto.ts
  src/main.ts
  src/product/dto/create-product.dto.ts
  src/product/dto/update-product.dto.ts
  src/product/product.controller.ts
Labels: status: Waiting For Review

#13 add 2 key to create-cat-dto
  src/cat/dto/create-cat.dto.ts
Labels: status: Waiting For Review

#18 add 2 keys of create product dto
  src/product/dto/create-product.dto.ts
Labels: status: Waiting For Review

#19 Add 5 commits
  src/cat/cat.schema.ts
  src/product/dto/create-product.dto.ts
  src/product/product.controller.ts
  src/product/product.schema.ts
Labels: status: Waiting For Review
